ALTER TABLE posts DROP FOREIGN KEY fk_idUser;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS posts CASCADE;

CREATE TABLE users(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL
);

CREATE TABLE posts(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  text VARCHAR(1000) NOT NULL,
  public BOOLEAN NOT NULL,
  idUser INT NOT NULL,
  CONSTRAINT fk_idUser FOREIGN KEY (id)
  REFERENCES users(id)
);